steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/gcp-ml-ops/bank-campaign-model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcp-ml-ops/bank-campaign-model']

- name: 'gcr.io/gcp-ml-ops/bank-campaign-model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/gcp-ml-ops/git'
  args: ['clone', 'https://github.com/Ashokkumarreddypolu/model-training-repo.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model-training-repo/bank_campaign_model_training.py', 'gs://airflowcloudbuild']

images:
- 'gcr.io/gcp-ml-ops/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY